import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Menu } from "../../components/molecules";
import ProviderGlobal from "../../store/provider/ProviderGlobal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Regresemos a nuestra casa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ProviderGlobal>
        <body className={inter.className}>
          <Menu />
          {children}
        </body>
      </ProviderGlobal>
    </html>
  );
}
